source $HOME/.bash_profile

case $- in
  *i*) ;;
    *) return;;
esac

export OSH=$HOME/.oh-my-bash
OSH_THEME="agnoster"

completions=(
  git
  composer
  ssh
)

aliases=(
  general
)

# python3 virtualenv
alias create="python3 -m virtualenv --python=python3 .venv"
alias activate="source ./.venv/bin/activate"
alias python=$(which python3)
# editor
alias emacs="emacs -nw"
# overwrite guard
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias ofd="xdg-open ."
if [[ "$OSTYPE" == "darwin"* ]]; then
   alias ofd = "open ."
fi

plugins=(
  git
  bashmarks
)

# gpg and ssh
if type gpg > /dev/null; then
	export SSH_KEY_PATH="$HOME/.ssh/config"
	export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
	export GPG_TTY=$(tty)
fi

# defaults
export LANG=en_US.UTF-8
export EDITOR="$(which emacs) -nw"
export GIT_EDITOR=$EDITOR

# utility functions
update-vscode () {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        wget 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64' -O /tmp/code_latest_amd64.deb
        if [[ $? -ne 0 ]]; then
           echo "Network error!" >&2
           return 1
        fi
        sudo dpkg -i /tmp/code_latest_amd64.deb
        return 0
    else
        echo "Not linux" >&2
        return 1
    fi
}

update-discord () {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        wget 'https://discord.com/api/download/stable?platform=linux&format=deb' -O /tmp/discord_latest_amd64.deb
        if [[ $? -ne 0 ]]; then
           echo "Network error!" >&2
           return 1
        fi
        sudo dpkg -i /tmp/discord_latest_amd64.deb
        return 0
    else
        echo "Not linux" >&2
        return 1
    fi       
}


source "$OSH"/oh-my-bash.sh
